### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by kyrylo**

### CODE REVIEW

**Comment by kyrylo** [comment]
Does the changelog look reasonable to you, @BrianHawley?

**Comment by BrianHawley** [comment]
@kyrylo looks good to me. Do you want to consider dropping the `required_ruby_version` to 1.8.7 too? That will allow the use of this gem directly or to speed up SortedSet in that Ruby version, even if you don't need to support versions that far back in airbrake-ruby.

**Comment by BrianHawley** [comment]
Either way, it looks good to release.

**Comment by kyrylo** [comment]
Sure, let's drop it down to 1.8.7

**Comment by BrianHawley** [comment]
Looks great!

**Review by BrianHawley — APPROVED** [review]

**Pull request merged**
